export class MhahLocalConstant {
  Ritu = {
    name: ['बसंत', 'ग्रीष्म', 'वर्षा', 'शरद', 'हेमंत', 'शीत'],
    name_en_UK: [
      'Spring',
      'Summer',
      'Monsoon',
      'Autumn',
      'Pre-Winter',
      'Winter',
    ],
  };
  Masa = {
    name: [
      'वैशाख',
      'ज्येष्ठ',
      'आषाढ़',
      'श्रावण',
      'भाद्रपद',
      'आश्विन',
      'कार्तिक',
      'मार्गशीर्ष',
      'पौष',
      'माघ',
      'फाल्गुन',
      'चैत्र',
    ],
    name_en_IN: [
      'Baisakha',
      'Jyestha',
      'Asadha',
      'Srabana',
      'Bhadraba',
      'Aswina',
      'Karttika',
      'Margasira',
      'Pausa',
      'Magha',
      'Phalguna',
      'Chaitra',
    ],
  };
  Raasi: {
    name: string[];
    name_en_UK: string[];
  } = {
    name: [
      'मेष',
      'वृषभ',
      'मिथुन',
      'कर्क',
      'सिंह',
      'कन्या',
      'तुला',
      'वृश्चिक',
      'धनु',
      'मकर',
      'कुंभ',
      'मीन',
    ],
    name_en_UK: [
      'Aries',
      'Taurus',
      'Gemini',
      'Cancer',
      'Leo',
      'Virgo',
      'Libra',
      'Scorpio',
      'Sagittarius',
      'Capricorn',
      'Aquarius',
      'Pisces',
    ],
  };
  Day = {
    name: [
      'रविवार',
      'सोमवार',
      'मंगलवार',
      'बुधवार',
      'गुरुवार',
      'शुक्रवार',
      'शनिवार',
    ],
    name_en_UK: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
  };
  Nakshatra = {
    name: [
      'अश्विनी',
      'द्विजा',
      'कृत्तिका',
      'रोहिणी',
      'मृगशिरा',
      'आर्द्रा',
      'पुनर्वसु',
      'पुष्य',
      'आश्लेषा',
      'मघा',
      'पूर्वफाल्गुनी',
      'उत्तरफाल्गुनी',
      'हस्ता',
      'चित्रा',
      'स्वाती',
      'विशाखा',
      'अनुराधा',
      'ज्येष्ठा',
      'मूला',
      'पूर्वाषाढ़ा',
      'उत्तराषाढ़ा',
      'श्रवण',
      'धनिष्ठा',
      'शतभिषा',
      'पूर्वभाद्रपद',
      'उत्तरभाद्रपद',
      'रेवती',
    ],

    name_en_IN: [
      'Ashwini',
      'Dwija',
      'Krittika',
      'Rohini',
      'Mrigashirsha',
      'Ardra',
      'Punarvasu',
      'Pushya',
      'Ashlesha',
      'Magha',
      'Purva Phalguni',
      'Uttara Phalguni',
      'Hasta',
      'Chitra',
      'Swati',
      'Vishakha',
      'Anuradha',
      'Jyeshtha',
      'Mula',
      'Purva Ashadha',
      'Uttara Ashadha',
      'Sravana',
      'Dhanishta',
      'Shatabhisha',
      'Purva Bhadrapada',
      'Uttara Bhadrapada',
      'Rebati',
    ],
  };
  Paksha = {
    name_en_IN: ['Shukla', 'Krishna'],
    name_en_UK: ['Waxing Moon', 'Waning Moon'],
    name: ['शुक्ल', 'कृष्ण'],
  };

  Tithi = {
    name: [
      'प्रतिपदा',
      'द्वितीया',
      'तृतीया',
      'चतुर्थी',
      'पंचमी',
      'षष्ठी',
      'सप्तमी',
      'अष्टमी',
      'नवमी',
      'दशमी',
      'एकादशी',
      'द्वादशी',
      'त्रयोदशी',
      'चतुर्दशी',
      'पूर्णिमा',
      'प्रतिपदा',
      'द्वितीया',
      'तृतीया',
      'चतुर्थी',
      'पंचमी',
      'षष्ठी',
      'सप्तमी',
      'अष्टमी',
      'नवमी',
      'दशमी',
      'एकादशी',
      'द्वादशी',
      'त्रयोदशी',
      'चतुर्दशी',
      'अमावस्या',
    ],
    name_en_IN: [
      'Padyami',
      'Vidhiya',
      'Thadiya',
      'Chavithi',
      'Panchami',
      'Shasti',
      'Sapthami',
      'Ashtami',
      'Navami',
      'Dasami',
      'Ekadasi',
      'Dvadasi',
      'Trayodasi',
      'Chaturdasi',
      'Punnami',
      'Padyami',
      'Vidhiya',
      'Thadiya',
      'Chaviti',
      'Panchami',
      'Shasti',
      'Sapthami',
      'Ashtami',
      'Navami',
      'Dasami',
      'Ekadasi',
      'Dvadasi',
      'Trayodasi',
      'Chaturdasi',
      'Amavasya',
    ],
  };
  Karna = {
    name_en_IN: [
      'Bawa',
      'Balava',
      'Kaulava',
      'Taitula',
      'Garaja',
      'Vanija',
      'Vishti',
      'Sakuna',
      'Chatushpada',
      'Nagava',
      'Kimstughana',
    ],
    name: [
      'बव',
      'बालव',
      'कौलव',
      'तैतिल',
      'गर',
      'वणिज',
      'विष्टि',
      'शकुनि',
      'चतुष्पद',
      'नाग',
      'किंस्तुघ्न',
    ],
  };
  Yoga = {
    name_en_IN: [
      'Vishkambha',
      'Prithi',
      'Ayushman',
      'Saubhagya',
      'Sobhana',
      'Atiganda',
      'Sukarman',
      'Dhrithi',
      'Soola',
      'Ganda',
      'Vridhi',
      'Dhruva',
      'Vyaghata',
      'Harshana',
      'Vajra',
      'Siddhi',
      'Vyatipata',
      'Variyan',
      'Parigha',
      'Siva',
      'Siddha',
      'Sadhya',
      'Subha',
      'Sukla',
      'Bramha',
      'Indra',
      'Vaidhruthi',
    ],
    name: [
      'विष्कुम्भ',
      'प्रीति',
      'आयुष्मान',
      'सौभाग्य',
      'शोभन',
      'अतिगंड',
      'सुकर्मा',
      'धृति',
      'शूल',
      'गंड',
      'वृद्धि',
      'ध्रुवा',
      'व्याघात',
      'हर्षण',
      'वज्र',
      'सिद्धि',
      'व्यतीपात',
      'वरीयान',
      'परिघ',
      'शिव',
      'सिद्ध',
      'साध्य',
      'शुभ',
      'शुक्ल',
      'ब्रह्म',
      'इन्द्र',
      'वैधृति',
    ],
  };
  Trinity = {
    name_en_IN: ['Brahma', 'Vishnu', 'Shiva'],
    name: ['ब्रह्मा', 'विष्णु', 'शिव'],
  };
  Guna = {
    name_en_IN: ['Rajas', 'Tamas', 'Satva'],
    name_en_UK: [
      'passion, activity, movement',
      'ignorance, inertia, laziness',
      'goodness, calmness, harmonious',
    ],
    name: ['रजस', 'तमस', 'सत्व'],
  };

  Gana = {
    name_en_IN: ['Devata', 'Manushya', 'Rakshasa'],
    name_en_UK: ['God', 'Human', 'Demon'],
    name: ['देवता', 'मनुष्य', 'राक्षस'],
  };
}
